name: Goszakup Parser
on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 30 минут
  workflow_dispatch:  # Позволяет запускать вручную
jobs:
  parse:
    runs-on: ubuntu-latest
    environment: parser-env  # Имя твоего окружения
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run parser
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python ad_parser.py
    - name: Commit and push seen_ads.json
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add seen_ads.json
        git commit -m "Update seen_ads.json" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
